<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ref
 * Date: Wed, 30 Jul 2014 09:03:27 +0000
 */

$conf['title'] = '威尔豪斯仓储';
$conf['lang'] = 'zh';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['proxy']['user'] = 'ref';
$conf['proxy']['pass'] = '<b>MTk4NDg0';

// end auto-generated content
